travis:
  secure:
    BINSTAR_TOKEN: kshvr5I+NxxePvovrpgOclPS6HbdvVdgD0/Y8eNsQRF76Ng7mKJFRiL4G5R/mLPL0FOBhjSxOZg3jOc6rBfkG8uE+uvITMz30POvN9iim5cAs/6Me5zmAfnDNOEQ6sGa1njM1hc7aLGymR0Hiu1MepitFe/uvqPwVbvEdO/oSZaS38Vghtx5hA3Ymluk96V0U8ukl+ua26V8zM/NrdBVlbjaOEli/Wnh5+5VE9Dmz4okc/vxlxl499yfbumTIK2MSb2d1wf+GkygOf+02ov/h4iQDaSTfrVlIAZRnrdh5ibx/E2vOwRoXbQJke6zPbLpMl2cC/dJHmtrt1OaJ9WN2kivzV3CxLzUx8fvhjIgrp+rkmJJ0jG+mATYD5yR5td1J7E0DrLOeljGSdA/U46lTUHoz7sXKwiGV/ik7Y+UD6Y+aNkVFAN8iwDnlqGwviBlkrzziFhunPSPmbkVJ82xhNAPbU112ONEzm5QCXrdAMbdKZoBIY6GIFvkH0tLFZRitaoKb1OJSs3HeFmvFiLrA1TeXj7u2c7yQKM6I8zVWGP/J+NafshkogI1psbtI+ym4/7INXk6gXwVL3GqDp5AphEFnnBtOw43w58qUwgAkfRqGOAcIgQZAQDEBAES2aYj2I7zmCBWDiphaWRVlJBllPIxvezAtnQEeUFnOmwdB7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
